version: "3.9"

services:
  cbt_backend:
    build: .
    container_name: cbt_backend
    command: gunicorn CBT_System.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./static:/app/static
    expose:
      - "8000"
    environment:
      POSTGRES_DB: cbt_db
      POSTGRES_USER: cbt_user
      POSTGRES_PASSWORD: "mb:GA7!YF67!QZ*"
      DB_HOST: db
      DB_PORT: 5432
      VIRTUAL_HOST: cbt.webuildx.xyz,www.cbt.webuildx.xyz
      LETSENCRYPT_HOST: cbt.webuildx.xyz,www.cbt.webuildx.xyz
      LETSENCRYPT_EMAIL: e.oguh@yahoo.com
    depends_on:
      - db
    networks:
      - proxy
      - default
    restart: always

  db:
    image: postgres:14
    container_name: cbt_db
    environment:
      POSTGRES_DB: cbt_db
      POSTGRES_USER: cbt_user
      POSTGRES_PASSWORD: "mb:GA7!YF67!QZ*"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
    restart: always

networks:
  proxy:
    external: true
  default:

volumes:
  postgres_data: